### PR TITLE
fixes test cases for wait file

### LINKED ISSUE #332: Unit test failing in Windows OS for cli runtime wait.go
### Please fill out the issue checklist below and provide ALL the requested information.

- [x] I reviewed open and closed Github issues that may be related to my problem.
- [x] I am reporting a bug that others will be able to reproduce.

### Describe the bug
Unit test failing in Windows OS for wait.go file test cases
OS: Windows
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
    	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x112c7a2]

### Expected behavior
All unit test cases are successful 

### Steps to Reproduce
clone apps-cli-plugin code git clone https://github.com/vmware-tanzu/apps-cli-plugin in windows and run go test ./....
### Version (Apps plugin version, Version of K8s running on cluster)
Put the output of the following commad
```sh
tanzu version && tanzu apps version
```

### PR DESCRIPTION
**Pull request by shaheerkootteeri**
Pull request

### What this PR does / why we need it

fixes test cases for wait file which was erroring when testing in windows OS

### Which issue(s) this PR fixes

Fixes #332 

### Describe testing done for PR

Validated unit test cases in mac as well as windows.

### CODE REVIEW

File: pkg/cli-runtime/wait/wait_test.go [hunk 1]
```diff
@@ -191,6 +191,13 @@ func TestUntilDelete(t *testing.T) {
 		name:    "smaller timeout",
 		timeout: time.Millisecond,
 		err:     context.DeadlineExceeded,
+		reactorFunc: func(action clitesting.Action) (bool, runtime.Object, error) {
```
Comment (shashwathi) [inline pkg/cli-runtime/wait/wait_test.go:194]: this test case should error out when context being done and not invoke get call. This change is altering how `context.DeadlineExceeded` error is generated.
If this test fails in windows, i would reduce the timeout nanosecond and see if that helps so it doesnt trigger the 2nd condition of the ticker

Comment (shaheerkootteeri) [reply pkg/cli-runtime/wait/wait_test.go:194]: changing that to Nano seconds are not working as it is expecting to have the reactorFunction.

File: pkg/cli-runtime/wait/wait_test.go [hunk 2]
```diff
@@ -158,7 +158,7 @@ func TestUntilDelete(t *testing.T) {
 	defer func() {
 		BackOffTime = previousBackOffTime
 	}()
-	BackOffTime = 10 * time.Millisecond
+	BackOffTime = 30 * time.Millisecond
```
Comment (shashwathi) [inline pkg/cli-runtime/wait/wait_test.go:161]: why not pass `BackOffTime` as func function parameter?

**Review by shashwathi — CHANGES_REQUESTED** [review]

File: pkg/cli-runtime/wait/wait_test.go (hunk 2 above)
Comment (shaheerkootteeri) [reply pkg/cli-runtime/wait/wait_test.go:161]: Do you mean adding Backofftime as a function parameter to UntilDelete ? 
Having the BackOfftime public enables calling function to reset the value from default.

**Review by odinnordico — APPROVED** [review]

**Review by warango4 — APPROVED** [review]

File: pkg/cli-runtime/wait/wait_test.go (hunk 2 above)
Comment (shashwathi) [reply pkg/cli-runtime/wait/wait_test.go:161]: overriding public variable is not great way to set a variable. In future to add tests can you see how this will become a problem?

Comment (shaheerkootteeri) [reply pkg/cli-runtime/wait/wait_test.go:161]: workload delete uses the untilDelete function in wait file , and if we remove this public variable and have it accept as a function parameter, we will need to have prepare for each test case that store the backOfftime in context for each of test case and in workload delete we pull the value back from context or default to 5 second.

**Review by shashwathi — APPROVED** [review]
