### PR TITLE
Removing namespace from service reference is not ignored

### LINKED ISSUE #17: workload update/apply - the removal of namespace from previously created --service-ref is ignored with incorrect message
### Please fill out the issue checklist below and provide ALL the requested information.

- [X] I reviewed open and closed Github issues that may be related to my problem.
- [X] I am reporting a bug that others will be able to reproduce.

### Describe the bug
When user removes a namespace from a previously created --service-ref entry which originally included namespace, the apps plugin doesn't think there's anything to change so the update is skipped.

### Expected behavior
removal of namespace should trigger an update to the --service-ref claim

### Steps to Reproduce
1. add the following --service-ref to an existing workload:
  * `tanzu apps workload apply [my-app] --service-ref my-db=rabbitmq.com/v1beta1:RabbitmqCluster:my-namespace:my-broker`
1. update the `my-db` service-ref (remove `:my-namespace`):
  * `tanzu apps workload apply [my-app] --service-ref my-db=rabbitmq.com/v1beta1:RabbitmqCluster:my-broker`

The result of the update should be that the my-namespace portion of the service-ref should be removed (after the diff is displayed and user-prompt accepted)

### Version (Apps plugin version, Version of K8s running on cluster)
apps version v0.4.0+

### Environment where the bug was observed (cloud, OS, etc)
TAP v0.5.0 on GKE

### PR DESCRIPTION
**Pull request by shashwathi**
### What this PR does / why we need it
Fix the bug when namespace is deleted from service reference and it was ignored in annotations. With this fix, annotations will be updated correctly.

### Which issue(s) this PR fixes
Fixes #17 

### Describe testing done for PR

Use the test cases in github issue

### CODE REVIEW

File: pkg/commands/workload.go [hunk 1]
```diff
@@ -256,28 +255,24 @@ func (opts *WorkloadOptions) ApplyOptionsToWorkload(ctx context.Context, workloa
 		}
 	}
 
-	sc := servicev1alpha1.NewServiceClaimWorkloadConfig()
 	for _, ref := range opts.ServiceRefs {
 		parts := parsers.DeletableKeyValue(ref)
+		deleteKey := parts[0]
```
Comment (rashedkvm) [inline pkg/commands/workload.go:260]: **nit**: This key is used for Merge and Delete
```suggestion
		serviceRefKey := parts[0]
```
