### PR TITLE
fix: Allow user to pass only git commit for git ref

### LINKED ISSUE #28: User must provide either --git-branch or --git-tag when creating a workload using --git-commit flag
### Description of problem

While researching an issue whereby a user is required to provide `--git-branch` in addition to `--git-tag` in order for workload create/update/apply to succeed, found out user has to provide either --git-tag, --git-branch or both if they want want to provide `--git-commit` in order to create the workload from a specific commit.
Yet, this issue is blocked by the usage of the current version of FluxCD Source Controller (0.16) in Tanzu Application Platform

### Proposed solution

1. Update the version of FluxCD
1. Remove client-side validation for mutual inclusion of (`--git-branch` or `--git-tag`) when `--git-commit` is provided

### Additional context
- https://github.com/vmware-tanzu/tanzu-cli-apps-plugins/commit/ef67dc59ae3fc853fa0719002a0e3012c302c3f7
- https://github.com/fluxcd/source-controller/issues/315
- https://github.com/fluxcd/source-controller/pull/462

Issue originally submitted by @warango4

### LINKED ISSUE #179: Weird behaviour in flag interaction when creating workload from git source
### Please fill out the issue checklist below and provide ALL the requested information.

- [x] I reviewed open and closed Github issues that may be related to my problem.
- [x] I am reporting a bug that others will be able to reproduce.

### Describe the bug

When creating a workload from git source, it is allowed to set git tag, git branch and git commit. When not setting at least one of those there is a message saying 
```bash
[--git-branch, --git-tag]: Required value: expected exactly one, got neither
```
This can be misleading for user and wouldn't know what's actually the way a workload should be created. 

Also, when updating `commit` field, `tag` field is deleted. Same if updating `tag`, then `commit` would be deleted

*WHEN UPDATING COMMIT*
image

image

*WHEN UPDATING TAG*
image

image

### Steps to Reproduce
- Create a workload 
```sh
tanzu apps workload create pet-clinic --git-repo https://github.com/sample-accelerators/spring-petclinic --type web --app spring-petclinic --git-commit 123 --git-branch main
```
- Update the workload 
```sh
tanzu apps workload update pet-clinic  --git-tag tap-1.2
```
- Delete the workload
```sh
tanzu apps workload delete pet-clinic -y
```
- Create the workload without `--git-tag`, `--git-commit` and `--git-branch`
See the error
```sh
Error: [--git-branch, --git-tag]: Required value: expected exactly one, got neither
Error: exit status 1
```

### Version (Apps plugin version, Version of K8s running on cluster)
Put the output of the following commad
```sh
tanzu version && tanzu apps version

version: v0.11.1
buildDate: 2022-02-14
sha: 4d578570
v0.0.0-dev
```

### PR DESCRIPTION
**Pull request by warango4**
Pull request

### What this PR does / why we need it
Because of a [FluxCD bug](https://github.com/fluxcd/source-controller/issues/315), apps plugin would not allow users to pass a git commit to take the source from when creating a workload, so there was always a need to specify either `--git-branch` or `--git-tag`. There is an [upstream fix](https://github.com/fluxcd/source-controller/pull/462) in the newer versions of FluxCD and TAP has been updated to use the latest (`v0.17.1+`), so apps plugin can also be updated to allow users to create their workload using only `--git-commit`

### Which issue(s) this PR fixes

Fixes #179 
Fixes #28 

### Describe testing done for PR

- Created workloads in cluster using the three flags (`--git-commit`, `--git-tag`, `--git-branch`), each separated, and combination of these. 
- Added/updated unit testing
- Updated e2e test

### Additional information or special notes for your reviewer

Signed-off-by: Wendy Arango <warango@vmware.com>

### CODE REVIEW

**Comment by heyjcollins** [comment]
git* flag validation can be removed given we can't predict the downstream behavior of FluxCD (or some other orchestrator configured in the supply chain).

**Review by odinnordico — APPROVED** [review]
LGTM

File: testing/e2e/workload_test.go [hunk 1]
```diff
@@ -660,7 +660,10 @@ func TestCreateFromGitWithAnnotations(t *testing.T) {
 			Name:         "Update the created workload",
```
Comment (shaheerkootteeri) [inline testing/e2e/workload_test.go:660]: Can we add a test case to create workload with just --git commit and/ or with combination ?

Comment (warango4) [reply testing/e2e/workload_test.go:660]: It ust have got deleted when I rebased this PR. Thanks for pointing it Shaheer.

**Review by anibmurthy — APPROVED** [review]

**Review by shaheerkootteeri — APPROVED** [review]
LGTM
