### PR TITLE
Fixed incorrect error message for workload create

### LINKED ISSUE #49: Apps plugin output is incorrect when a user does not have permission to create workloads / Cartographer is not installed
### Please fill out the issue checklist below and provide ALL the requested information.

- [x] I reviewed open and closed Github issues that may be related to my problem.
- [x] I am reporting a bug that others will be able to reproduce.

### Describe the bug
While testing Apps plugin behavior with users having different RBAC permissions, I found out that when a user who does not have permission to create a workload tries to run `tanzu apps workload create` command, apps plugin responds with an incorrect message.

### Running `$ tanzu apps workload create petc --local-path .` on a Kind cluster with no Cartographer/TAP/AppToolkit installed.

```
API Error name:tanzu apps  error:no matches for kind "Workload" in version "carto.run/v1alpha1"
Error: workload "default/petc" already exists
Error: exit status 1

✖  exit status 1
```

### Expected behavior
```
Error: You don't have Cartographer/TAP/AppToolkit installed on your cluster. Please proceed to install it before using this plugin.
Error: exit status 1

✖  exit status 1
```

### Running `$ tanzu apps workload create petc-adhol --local-path .` on a TAP installed cluster with Pinniped installed where user does not have the permission to create workloads.

```
API Error name:tanzu apps  error:workloads.carto.run "petc-adhol" is forbidden: User "rlee+app-viewer@pivotal.io" cannot get resource "workloads" in API group "carto.run" in the namespace "default": decision made by impersonation-proxy.concierge.pinniped.dev
Error: workload "default/petc-adhol" already exists
Error: exit status 1

✖  exit status 1
```

### Expected behavior
```
Error: workloads.carto.run "petc-adhol" is forbidden: User "rlee+app-viewer@pivotal.io" cannot get resource "workloads" in API group "carto.run" in the namespace "default": decision made by impersonation-proxy.concierge.pinniped.dev
Error: exit status 1

✖  exit status 1
```

### Version (Apps plugin version, Version of K8s running on cluster)
Apps Plugin version 0.5.1

### PR DESCRIPTION
**Pull request by rashedkvm**
Signed-off-by: Rashed Kamal <krashed@vmware.com>

Pull request

### What this PR does / why we need it

This PR fixes the incorrect error message displayed during `tanzu apps workload create ...` scenarios. 

### Which issue(s) this PR fixes

Fixes #49 

### Describe testing done for PR

- Passes all unit test
- Functional tests ran locally

_When cartographer CRD not installed in the target cluster_
```
tanzu apps workload apply -f ./pkg/commands/testdata/workload.yaml

Error: no matches for kind "Workload" in version "carto.run/v1alpha1"
Error: exit status 1
```

_When workload already exists_
```
tanzu apps workload create -f ./pkg/commands/testdata/workload.yaml
Error: workload "default/spring-petclinic" already exists
Error: exit status 1
```

_When workload does not exist_
```
tanzu apps workload create -f ./pkg/commands/testdata/workload.yaml
Create workload:
      1 + |---
      2 + |apiVersion: carto.run/v1alpha1
      3 + |kind: Workload
      4 + |metadata:
      5 + |  labels:
      6 + |    app.kubernetes.io/part-of: spring-petclinic
      7 + |    apps.tanzu.vmware.com/workload-type: web
      8 + |  name: spring-petclinic
      9 + |  namespace: default
     10 + |spec:
     11 + |  env:
     12 + |  - name: SPRING_PROFILES_ACTIVE
     13 + |    value: mysql
     14 + |  resources:
     15 + |    limits:
     16 + |      cpu: 500m
     17 + |      memory: 1Gi
     18 + |    requests:
     19 + |      cpu: 100m
     20 + |      memory: 1Gi
     21 + |  source:
     22 + |    git:
     23 + |      ref:
     24 + |        branch: main
     25 + |      url: https://github.com/spring-projects/spring-petclinic.git

Do you want to create this workload? Yes
Created workload "spring-petclinic"
```

### Additional information or special notes for your reviewer

There is an extra error line displayed before this fix. Fix for the additional error line will be addressed in a separate PR.

`API Error name:tanzu apps  error:workloads.carto.run "spring-petclinic" not found`

### CODE REVIEW

File: pkg/commands/workload_create.go [hunk 1]
```diff
@@ -68,9 +69,23 @@ func (opts *WorkloadCreateOptions) Exec(ctx context.Context, c *cli.Config) erro
...
+	existingWorkload := &cartov1alpha1.Workload{}
+
+	err := c.Get(ctx, client.ObjectKey{Namespace: workload.Namespace, Name: workload.Name}, existingWorkload)
+
+	if err != nil {
+		// return err, except when not found
+		if !apierrs.IsNotFound(err) {
+			return err
+		}
+	}
```
Comment (warango4) [inline pkg/commands/workload_create.go:81]: Do you think that maybe something like this would work?
```suggestion
         // return err, except when not found
        if err := c.Get(ctx, client.ObjectKey{Namespace: workload.Namespace, Name: workload.Name}, existingWorkload); err != nil && !apierrs.IsNotFound(err) {
		return err
	}
```

Comment (rashedkvm) [reply pkg/commands/workload_create.go:81]: Good point @warango4. I was checking `err` object for two different `apierrs`, but the second check was not valuable. However, your suggestion is spot on as we are down to a single statement. I will update the PR.

**Review by warango4 — APPROVED** [review]

File: pkg/commands/workload_create.go [hunk 2]
```diff
@@ -68,9 +69,21 @@ func (opts *WorkloadCreateOptions) Exec(ctx context.Context, c *cli.Config) erro
...
+
+	if err := c.Get(ctx, client.ObjectKey{Namespace: workload.Namespace, Name: workload.Name}, existingWorkload); err != nil {
+		// return err, except when not found
+		if !apierrs.IsNotFound(err) {
+			return err
+		}
+	}
+
+	// check if the workload exists
+	if existingWorkload != nil {
```
Comment (shashwathi) [inline pkg/commands/workload_create.go:82]: you can merge both if conditions

Comment (shashwathi) [reply pkg/commands/workload_create.go:82]: If you can merge it, we avoid an untested branch. If existingWorkload is nil, then rest of the conditions are not executed either in Go.

**Review by odinnordico — APPROVED** [review]
LGTM

File: pkg/commands/workload_create.go (hunk 2 above)
Comment (rashedkvm) [reply pkg/commands/workload_create.go:82]: @shashwathi Are you asking to merge `err` and `existingWorkload` checks in a single `if` statement? These are two different objects and do not follow your comment.

Comment (shashwathi) [reply pkg/commands/workload_create.go:82]:
```suggestion
	if existingWorkload != nil && existingWorkload.Name == workload.Name && existingWorkload.Namespace == workload.Namespace {
	c.Printf("%s workload %q already exists\n", printer.Serrorf("Error:"), fmt.Sprintf("%s/%s", workload.Namespace, workload.Name))
			return cli.SilenceError(err)
			}
```

Comment (rashedkvm) [reply pkg/commands/workload_create.go:82]: Both suggested and implemented change work in this particular `if` statement. However, the implemented code is easier to read. Therefore, we are going with the PR implementation. Thank you for the suggestion.
