### PR TITLE
Fixes file path issue in client test file for windows

### LINKED ISSUE #330: Unit test failing in Windows OS for file Path in client test and config test
### Please fill out the issue checklist below and provide ALL the requested information.

- [x] I reviewed open and closed Github issues that may be related to my problem.
- [x] I am reporting a bug that others will be able to reproduce.

### Describe the bug

Unit test failing in Windows OS for file Path in client test and config test with below error
OS: Windows 
Error: error loading config file "testdata/.kube/config:": open testdata/.kube/config:: The filename, directory name, or volume label syntax is incorrect.

### Expected behavior
Unit test should be successful
### Steps to Reproduce
clone apps-cli-plugin code `git clone https://github.com/vmware-tanzu/apps-cli-plugin` in windows and run `go test ./....` 
### Version (Apps plugin version, Version of K8s running on cluster)
Put the output of the following commad
```sh
tanzu version && tanzu apps version
```

### PR DESCRIPTION
**Pull request by shaheerkootteeri**
Pull request

### What this PR does / why we need it
PR fixes client and config package test cases to support all OS file paths. 

### Which issue(s) this PR fixes

Fixes #330 

### Describe testing done for PR

Reran all the unit test cases in Mac as well as windows OS, also ran make commands to install successfully.

### CODE REVIEW

File: pkg/cli-runtime/client_test.go [hunk 1]
```diff
@@ -34,7 +36,7 @@ func TestNewClient(t *testing.T) {
 	scheme := runtime.NewScheme()
 	clitestingresource.AddToScheme(scheme)
 
-	c := NewClient("testdata/.kube/config", "", scheme)
+	c := NewClient(filepath.Join("testdata", ".kube", "config"), "", scheme)
```
Comment (shashwathi) [inline pkg/cli-runtime/client_test.go:39]: path for the testdata folder remains the same across all tests so declare the var globally and use the same in all tests

File: pkg/cli-runtime/client_test.go [hunk 2]
```diff
@@ -30,11 +32,13 @@ import (
 	clitestingresource "github.com/vmware-tanzu/apps-cli-plugin/pkg/cli-runtime/testing/resource"
 )
 
+var configPath = filepath.Join("testdata", ".kube", "config")
```
Comment (shashwathi) [inline pkg/cli-runtime/client_test.go:35]: `kubeConfigPath` instead of `configPath`

File: pkg/cli-runtime/config_pkg_test.go [hunk 3]
```diff
@@ -64,12 +64,12 @@ func TestInitKubeConfig_Flag(t *testing.T) {
 	c.Stdout = output
 	c.Stderr = output
 
-	c.KubeConfigFile = "testdata/.kube/config"
+	c.KubeConfigFile = configPath
```
Comment (shashwathi) [inline pkg/cli-runtime/config_pkg_test.go:67]: nit : not a fan of using a var from other test file. It would be great if its all local to this test file or test case.

**Review by shashwathi — APPROVED** [review]
